name: Allow pull

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Análisis de SAST
        run: echo "Realizando análisis de SAST"

      - name: Get allow pull
        id: allow-pull-var
        run: |
          if [ -f allow_pull_request.txt ]; then
            echo "ALLOW_PULL=true" >> $GITHUB_OUTPUT
          else
            echo "ALLOW_PULL=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Imprimir mensaje
        env: 
          ALLOW_PULL: ${{ steps.allow-pull-var.outputs.ALLOW_PULL }}
        run: |
          echo "$ALLOW_PULL"
          if [ "$ALLOW_PULL" == true ]; then
            echo "Permitiendo Pull Request."
          else
            echo "Build fallida. Impidiendo Pull Request."
            exit 1
          fi
