name: Allow pull

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Análisis de SAST
        run: echo "Realizando análisis de SAST"
          
      - name: Check if allow_pull_request.txt exists and set environment variable
        run: |
          if [ -f allow_pull_request.txt ]; then
            echo "::set-env name=ALLOW_PULL::true"
          else
            echo "::set-env name=ALLOW_PULL::false"
          fi

      - name: Print allow_pull 
        run: echo "allow_pull=${{ env.ALLOW_PULL }}"

      - name: Imprimir mensaje
        run: |
          if [ "${{ env.ALLOW_PULL }}" == "true" ]; then
            echo "Permitiendo Pull Request."
          else
            echo "Build fallida. Impidiendo Pull Request."
            exit 1
          fi