name: Allow pull

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Análisis de SAST
        run: echo "Realizando análisis de SAST"

      - name: Check if allow_pull_request.txt exists
        run: |
          if [ -f allow_pull_request.txt ]; then
            export allow_pull=true
          else
            export allow_pull=false
          fi
          
      - name: Print allow_pull variable
        run: echo "allow_pull=$allow_pull"

      - name: Print current directory file list
        run: ls -al

      - name: Imprimir mensaje
        run: |
          if [ "$allow_pull" == "true" ]; then
            echo "Permitiendo Pull Request."
          else
            echo "Build fallida. Impidiendo Pull Request."
            exit 1
          fi

